# Generated by Django 4.1.2 on 2022-11-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(default='aaaaa', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
